name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Test on Python 3.8, 3.9, and 3.10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Set up Python for each version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install googlesearch-python colorama tabulate

    - name: Install flake8
      run: |
        pip install flake8

    - name: Lint with flake8
      run: |
        # Run flake8 using the .flake8 config file that ignores non-critical errors
        flake8 CortexLink.py || true  # Ensure flake8 errors don't stop the build

    - name: Run tests
      run: |
        echo "No tests available"
