name: Python Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    # Use the latest Ubuntu image to run the job
    runs-on: ubuntu-latest

    # Define supported Python versions (Python 3.1 is not supported)
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # These are valid Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Set up Python using valid versions
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install googlesearch-python colorama tabulate

    - name: Install flake8
      run: |
        pip install flake8

    - name: Lint with flake8
      run: |
        # Explicitly point to the .flake8 configuration file
        flake8 --config .flake8 CortexLink.py || true  # Ensure flake8 errors don't stop the build

    - name: Run tests
      run: |
        echo "No tests available"
